<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFrameworks>net10.0;net48</TargetFrameworks><LangVersion>latest</LangVersion><AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
    <PackageReference Include="PolySharp" Version="1.15.0" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="10.0.11" />
    <PackageReference Include="System.Text.Json" Version="10.0.12" />
    <PackageReference Include="System.Threading.Channels" Version="10.0.11" />
  </ItemGroup>
</Project>
